# `clang++-7` compiles our program (++ means c++, -7 means the version of clang to use)
# `std` is an option telling clang which version of C++ we want to compile with
# `-o` is an option telling clang what the compiled program should be named
# `main.cpp` is the C++ file we want to compile
# `&&` makes sure both sides of the operation succeed (in this case, compile and run steps)
# `./main` runs the compiled program generated by clang
clang++-7 -std=c++11 -o game game.cpp && ./game